[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026F1AC5B6E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/66c664508fee645093f8d39812082f5c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026F1AC5A960>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/66c664508fee645093f8d39812082f5c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026F1AC5BA70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/66c664508fee645093f8d39812082f5c