[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026F1AC5AC30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aaceab95cf609a674ccb826d6b737d0f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026F1AC5A870>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aaceab95cf609a674ccb826d6b737d0f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026F1AC5A960>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aaceab95cf609a674ccb826d6b737d0f